# Numpy Tutorial
**Data Mining Lab, University of Victoria, Summer2020** <br>
(Y.Sant)

In [ ]:
import sklearn as sk
import numpy as np
import scipy
import pandas

In [82]:
from sklearn.datasets import load_wine, load_iris, load_boston, load_diabetes
from sklearn import tree
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics


In [76]:
data_set = load_iris
data = data_set()
print(data.data.shape)

decision_tree = tree.DecisionTreeClassifier(max_depth=3, criterion='entropy') # min_impurity_decrease = 0.5, min_samples_split = 10 

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=0)
print(X_train.shape)
clf = decision_tree.fit(X_train, y_train)
y_pred = clf.predict(X_test)

(150, 4)
(120, 4)


In [79]:
#tree.plot_tree(clf) if we had matplotlib, it would work!
# Graphviz!

In [83]:
visual = tree.export_text(clf, feature_names=data['feature_names'])
print(visual)

|--- petal width (cm) <= 0.80
|   |--- class: 0
|--- petal width (cm) >  0.80
|   |--- petal width (cm) <= 1.75
|   |   |--- petal length (cm) <= 4.95
|   |   |   |--- class: 1
|   |   |--- petal length (cm) >  4.95
|   |   |   |--- class: 2
|   |--- petal width (cm) >  1.75
|   |   |--- petal length (cm) <= 4.85
|   |   |   |--- class: 1
|   |   |--- petal length (cm) >  4.85
|   |   |   |--- class: 2



In [72]:
#  abs(y_actual - y_pred)
#  (y_actual - y_pred)^2
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
# Why Mean Absolute Error and Mean Squared Error are the same? Is it always like that in classification?
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

Mean Absolute Error: 0.03333333333333333
Mean Squared Error: 0.03333333333333333
Root Mean Squared Error: 0.18257418583505536
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


Post-Pruning
1. https://stackoverflow.com/questions/49428469/pruning-decision-trees
2. To do post pruning you could search cost_complexity_pruning.

In [23]:
data_set = load_diabetes
data = data_set()
print(data['feature_names'])
decision_tree = tree.DecisionTreeRegressor(max_depth=3)

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=0)

clf = decision_tree.fit(X_train, y_train)
y_pred = clf.predict(X_test)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [24]:
visual = tree.export_text(clf, feature_names=data['feature_names'])
print(visual)


|--- s5 <= 0.02
|   |--- bmi <= 0.01
|   |   |--- s3 <= 0.02
|   |   |   |--- value: [115.77]
|   |   |--- s3 >  0.02
|   |   |   |--- value: [86.21]
|   |--- bmi >  0.01
|   |   |--- bp <= 0.02
|   |   |   |--- value: [147.22]
|   |   |--- bp >  0.02
|   |   |   |--- value: [219.59]
|--- s5 >  0.02
|   |--- bmi <= 0.01
|   |   |--- bp <= 0.06
|   |   |   |--- value: [167.43]
|   |   |--- bp >  0.06
|   |   |   |--- value: [261.25]
|   |--- bmi >  0.01
|   |   |--- bmi <= 0.06
|   |   |   |--- value: [225.19]
|   |   |--- bmi >  0.06
|   |   |   |--- value: [263.23]



In [25]:

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
# Why Mean Absolute Error and Mean Squared Error are the same? Is it always like that in classification?
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 55.703794688457606
Mean Squared Error: 4778.141926493388
Root Mean Squared Error: 69.12410524913425


In [30]:
# Random Forest

from sklearn.model_selection import train_test_split
data_set = load_iris
data = data_set()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=0)

In [31]:
classifier = RandomForestClassifier(n_estimators=20, random_state=0, max_features='sqrt') 
# 'auto' = 'sqrt' ==> sqrt(d)
# None ==> d
# int 

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [32]:


print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
# Why Mean Absolute Error and Mean Squared Error are the same? Is it always like that in classification?
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

Mean Absolute Error: 0.03333333333333333
Mean Squared Error: 0.03333333333333333
Root Mean Squared Error: 0.18257418583505536
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [33]:
# What is Random State?
regressor = RandomForestRegressor(n_estimators=20, random_state=0, max_features='auto')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [34]:

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.03166666666666667
Mean Squared Error: 0.012416666666666668
Root Mean Squared Error: 0.11143009766964519


# Numpy
**Data Mining Lab, University of Victoria, Spring 2020** <br>


In [35]:
import numpy as np

# The import below is needed so that we can display full output in Jupyter, not only the last result.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Arrays
--

The main entity in Numpy is the "array". Arrays are also called tensors. <br>
A two-dimensional array is also called a matrix.

**Dimensions, shapes and sizes (properties)** <br>
ndim = the number of dimensions <br>
shape = the dimensions (in a tuple) <br>
size = number of elements (= the product of the numbers in the shape)

In [36]:
a = np.array([1, 2, 3])     # A 1-dimensional array
a
a.ndim
a.shape
a.size

array([1, 2, 3])

1

(3,)

3

In [37]:
b = np.array([[1, 2, 3]])   # A row vector
b
b.ndim
b.shape
b.size

array([[1, 2, 3]])

2

(1, 3)

3

In [38]:
c = np.array([[1], [2], [3]])   # A column vector
c
c.ndim
c.shape
c.size

array([[1],
       [2],
       [3]])

2

(3, 1)

3

In [39]:
d = np.array([
[1,2,3],
[4,5,6]])   # A 2x3 matrix
d
d.ndim
d.shape
d.size

array([[1, 2, 3],
       [4, 5, 6]])

2

(2, 3)

6

In [40]:
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # A 3-D array
e
e.ndim
e.shape
e.size

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

3

(2, 2, 2)

8

In [41]:
# Create a 3x4 array of zeros
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
# Create a 3x4 array of ones
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
# Create an array of the given shape and populate it 
# with random samples from a uniform distribution over [0, 1).

x = np.random.rand(3,4)
print(x)

[[0.64352212 0.83596061 0.31463682 0.40767017]
 [0.89680913 0.546069   0.41451915 0.46944497]
 [0.25798654 0.01194038 0.5962134  0.43049454]]


In [44]:
# Create an array of the given shape and populate it 
# with random samples from "standard normal" distribution
# (mean = 0, var = 1).

x = np.random.randn(3,4)
print(x)

[[-1.01549183  1.32026723 -0.22747186  1.51917605]
 [ 1.43585796 -1.32029682 -0.88531403 -0.87144079]
 [-1.04138542 -1.83249381 -0.24163374  0.52681591]]


In [45]:
# We can get a specific element on an array by using indices
d
d[0,2]
d[1,1]

array([[1, 2, 3],
       [4, 5, 6]])

3

5

Matrix Math
--

In [47]:
x = np.array( [[1,2],[3,4]] )
y = np.array( [[5,6],[7,8]] )
# Elementwise sum
z = x + y
print ("x+y = \n", z, "\n")

# Elementwise difference
z = x - y
print ("x-y = \n", z, "\n")

# Elementwise product
z = x * y
print ("x*y = \n", z, "\n")

x+y = 
 [[ 6  8]
 [10 12]] 

x-y = 
 [[-4 -4]
 [-4 -4]] 

x*y = 
 [[ 5 12]
 [21 32]] 



In [48]:
# Matrix dot product; 
# There are three different ways -- same result
z = x.dot(y)
print ("x.dot(y) = \n", z, "\n")

z = np.dot(x, y)
print ("np.dot(x, y) = \n", z, "\n")

z = x @ y     # Only in Python 3
print ("x @ y = \n", z, "\n")

x.dot(y) = 
 [[19 22]
 [43 50]] 

np.dot(x, y) = 
 [[19 22]
 [43 50]] 

x @ y = 
 [[19 22]
 [43 50]] 



**Note:** 
* For dot product, the shapes of the two matrices must match. <br>
In the example above we have (2x2) @ (2x2), which match, so it works.
For another example we can have (2x3) @ (3x1), the 3s match. <br>
but not (2x2) @ (3x2)  (This won't work.)
* Dot product is not commutative. In general x @ y is not equal to y @ x
* This can be applied to arrays of higher dimensions as well.

In [50]:
# Matrix transpose
z = x.T
print ("x.T = \n", z, "\n")

x.T = 
 [[1 3]
 [2 4]] 



In [51]:
# Multiplying a matrix with a number
z = x * 2
print ("x*2 = \n", z, "\n")

x*2 = 
 [[2 4]
 [6 8]] 



Reshaping Arrays
--

In [52]:
x = np.random.randn(3,4)
print("x = \n",x)

z = np.reshape(x, (4,3))
print("z = \n", z)

z2 = np.reshape(x, (2,6))
print("z2 = \n", z2)

x = 
 [[ 0.48750824 -0.63422158  0.73464541 -0.46201682]
 [-0.94645081  0.28387444 -0.70994916  1.00226156]
 [ 0.46343723  1.11140198  0.27641839 -1.5246794 ]]
z = 
 [[ 0.48750824 -0.63422158  0.73464541]
 [-0.46201682 -0.94645081  0.28387444]
 [-0.70994916  1.00226156  0.46343723]
 [ 1.11140198  0.27641839 -1.5246794 ]]
z2 = 
 [[ 0.48750824 -0.63422158  0.73464541 -0.46201682 -0.94645081  0.28387444]
 [-0.70994916  1.00226156  0.46343723  1.11140198  0.27641839 -1.5246794 ]]


In [53]:
# We will often want to reshape 2D images to nx1 or 1xn arrays.

z = np.reshape(x,(x.shape[0]*x.shape[1],1))
# or
#z = x.reshape((x.shape[0]*x.shape[1],1))

print("z = \n", z)

z = 
 [[ 0.48750824]
 [-0.63422158]
 [ 0.73464541]
 [-0.46201682]
 [-0.94645081]
 [ 0.28387444]
 [-0.70994916]
 [ 1.00226156]
 [ 0.46343723]
 [ 1.11140198]
 [ 0.27641839]
 [-1.5246794 ]]


Array Slicing
--
Array slicing is similar to list slicing, but here we need to do slicing in each dimension.

In [54]:
# Let's create an array
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# Slice in the 1st dimension from 0 to 2 (not including 2)
# Slice in the 2nd dimension from 1 to 3 (not including 3)
b = a[0:2, 1:3]

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [55]:
# The previous example can also be written as follows.
# We don't need to specify 0. 
b = a[:2, 1:3]

print(b)

[[2 3]
 [6 7]]


In [56]:
# Here is another example
b = a[:2, 1:4]

print(b)

[[2 3 4]
 [6 7 8]]


In [57]:
# The previous example can also be written as follows.
# We don't need to specify 4. 
b = a[:2, 1:]

print(b)

[[2 3 4]
 [6 7 8]]


In [58]:
# Negative indexes are used to count backwards from the end of a range. 
# Suppose we want all the rows of an array, and all the columns, except the last column.

# Let's recall a
print("a = \n", a)

# Now let's take the slice we want
b = a[:, :-1]

print("b = \n", b)

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b = 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


Numpy Math Functions
--

In [59]:
# Let's create a 1x3 array
a = np.array([[1,2,3,4]])

# compute e^x for each number in the array
print("np.exp(a) = \n", np.exp(a))

# compute the log (base e) of each number in the array
print("np.log(a) = \n", np.log(a))

# See, numpy functions, such as exp and log, 
# take arrays as input and produce arrays as output. 
# They compute the function on each element of the input array.

np.exp(a) = 
 [[ 2.71828183  7.3890561  20.08553692 54.59815003]]
np.log(a) = 
 [[0.         0.69314718 1.09861229 1.38629436]]


**The Sigmoid Function**

An important function in neural networks is the Sigmoid function, sometimes known as the logistic function
$$
sigmoid(x) = \frac{1}{1+e^{-x}}.
$$
Let's implement it using numpy.

In [60]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

sigmoid(a)

array([[0.73105858, 0.88079708, 0.95257413, 0.98201379]])

**Axis and keepdims**

Some numpy functions, such as sum, avg, min, max, etc, take as input an array and return a number, e.g. the sum, average, min, max of the elements of the array. What if we want the sum, average, min, max of each row or each column? For this we use *axis* and *keepdims*. See examples below.

In [61]:
# Let's create an array
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a

# Sum of all elements in the array
np.sum(a)

# Sum of elements in each column
np.sum(a, axis=0)

# Sum of elements in each row
np.sum(a, axis=1)

# The problem with the above is that the result is not a 2D array. 
# If we need the result to be a 2D array, specify keepdims=True.

np.sum(a, keepdims=True)

np.sum(a, axis=0, keepdims=True)

np.sum(a, axis=1, keepdims=True)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

78

array([15, 18, 21, 24])

array([10, 26, 42])

array([[78]])

array([[15, 18, 21, 24]])

array([[10],
       [26],
       [42]])

Broadcasting
--
We can perform operations with arrays of different shapes. For example suppose we have an array 
$$
a = \begin{bmatrix}
    1 & 2 & 3 & 4  \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 
\end{bmatrix}
$$
and would like to multiply it with 
$$
b = \begin{bmatrix}
    1 \\
    5 \\
    9  
\end{bmatrix}
$$
If we say $a*b$, array $b$ will be first expanded (broadcast) to 
\begin{bmatrix}
    1 & 1 & 1 & 1\\
    5 & 5 & 5 & 5\\
    9 & 9 & 9 & 9 
\end{bmatrix}
then element-wise multiplication will be performed. 

In [62]:
a

b = np.array([[1],[5],[9]])

b

a*b

a+b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[1],
       [5],
       [9]])

array([[  1,   2,   3,   4],
       [ 25,  30,  35,  40],
       [ 81,  90,  99, 108]])

array([[ 2,  3,  4,  5],
       [10, 11, 12, 13],
       [18, 19, 20, 21]])

In [63]:
x = np.linspace(0, 10, 40)

x

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

## Some simple plotting examples

In [65]:
import matplotlib.pyplot as plt
%matplotlib inline
sinx = np.sin(x)
plt.plot(x, sinx)


ModuleNotFoundError: No module named 'matplotlib'

In [66]:
x.reshape(4, 10)
cosx = np.cos(x)
plt.plot(x, sinx, 'o')
plt.plot(x, cosx, 'x')


array([[ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
         1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231],
       [ 2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
         3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487],
       [ 5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
         6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744],
       [ 7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
         8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ]])

NameError: name 'plt' is not defined

In [67]:
y = sinx * cosx
z = cosx ** 2 - sinx ** 2
plt.plot(x, y)
plt.plot(x, z)
plt.legend(['sin(x) cos(x)', 'cos(x)^2 - sin(x)^2'])
# http://matplotlib.org/users/legend_guide.html


NameError: name 'sinx' is not defined

In [68]:
np.save('array.npy', a)
loaded_array = np.load('array.npy')
loaded_array


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])